### ISSUE TITLE
Package Mesos for Debian stretch?

### ISSUE THREAD

**Issue by chriskuehl** [mesosphere/mesos-deb-packaging#109]
[Debian stretch](https://www.debian.org/News/2017/20170617.en.html) was released yesterday and is now the new Debian "stable". Would you please consider building Mesos packages for it, in addition to the packages currently built for Debian jessie (old stable)?

**Comment by ivucica** [comment]
It's worse: there is actual breakage when old packages are involved.

I happen to be running the latest Debian Stretch on one of my machines, so old packages should be fixed to add a runtime dependency: `libssl1.0.0`.

```
Jul  8 13:54:02 some-hostname-heree mesos-slave[7000]: /usr/sbin/mesos-slave: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

If I just want to make it run, that's a problem as well. Stretch does not include `libssl1.0.0` and I do have `libssl1.0.2` and `libssl1.1` installed. Neither seems to be binary-compatible with `libssl1.0.0` as `mesos-slave` fails to find a specific symbol in them (something like `OPENSSL_1.0.0`); I've tried symlinking relevant libraries over there.

There is no packaging uploaded for `zesty` or `artful` Ubuntu either, so that's not a workaround, either.

So, to prevent pain, can you add a runtime dep to existing `mesos` package? Separately, can you build a package for Stretch?

**Comment by schneidexe** [comment]
+1

**Comment by zolech** [comment]
+1

**Comment by syndbg** [comment]
Ping. Almost 2 months time for just a Stretch package is too much.

**Comment by radekg** [comment]
It seems like a community fork of this project is a good idea. There's zero response to any issue from Mesosphere here.

**Comment by syndbg** [comment]
A workaround at the moment is to do:

# By adding `jessie-backports`

```shell
> echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
> apt -q update
> apt install -y libssl1.0.0
> echo "deb http://repos.mesosphere.io/debian jessie main" > /etc/apt/sources.list.d/mesosphere.list
> apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
> apt -q update
> apt -y install mesos=1.3.0-2.0.3
```

# By avoiding `jessie-backports

Pick a package from https://packages.debian.org/jessie-backports/amd64/libssl1.0.0/download to download and install as in:

```shell
> wget http://ftp.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb
> dpkg -i libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb
> echo "deb http://repos.mesosphere.io/debian jessie main" > /etc/apt/sources.list.d/mesosphere.list
> apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
> apt -q update
> apt -y install mesos=1.3.0-2.0.3
```

**Comment by timcharper** [comment]
@syndbg This is a partial workaround and will work fine so long as you are not using SSL with Mesos. Otherwise, in my experience, it will crash.

**Comment by syndbg** [comment]
Still no Debian Trusty support.

The seriousness of this project is becoming a joke, given that people actually use this in production.

At this point I'm fairly certain moving to Kubernetes is a natural decision.

**Comment by timcharper** [comment]
I was able to build this pretty easily using docker:


```
git clone https://github.com/mesosphere/mesos-deb-packaging
docker run -it -v $(pwd)/mesos-deb-packaging /mesos-deb-packaging
apt-get install -y  ruby ruby-dev python-dev autoconf automake git make libssl-dev libcurl3 libtool
gem install fpm
apt-get install -y openjdk-8-jdk
apt-get install -y build-essential python-dev python-six python-virtualenv libcurl4-nss-dev libsasl2-dev libsasl2-modules maven libapr1-dev libsvn-dev zlib1g-dev

export MAKEFLAGS=-j8 # or how many cores avail
export MAINTAINER="Name <name@email.com>"
cd /mesos-deb-packaging
./build_mesos --repo https://git-wip-us.apache.org/repos/asf/mesos.git?ref=1.4.0
```

You'll have a file named `deb.pkg` in the end

**Comment by chriseatworld** [comment]
+1

**Comment by artemharutyunyan** [comment]
@syndbg sorry about that. @karya0 is working to address this asap.

**Comment by karya0** [comment]
@syndbg @chriskuehl @chriseatworld @artemharutyunyan: The debian stretch package for Mesos 1.4.1 is now available at:
http://repos.mesosphere.com/debian/pool/main/m/mesos/mesos_1.4.1-2.0.1.debian9_amd64.deb

The 1.4.0, 1.3.1, 1.2.2, and 1.1.3 are on their way and should be available in a few hours.

**Comment by syndbg** [comment]
@artemharutyunyan @karya0 Thank you.

**Comment by csaltos** [comment]
@artemharutyunyan @karya0 Thank you !! 👍
