### ISSUE TITLE
Mesos-master and mesos-slave should be installed as services...

### ISSUE THREAD

**Issue by swartzrock** [mesosphere/mesos-deb-packaging#36]
According to https://mesosphere.com/docs/reference/packages/ it is possible to start the mesos-master and mesos-slave services with these commands:

    sudo service (start | stop | restart) mesos-master
    sudo service (start | stop | restart) mesos-slave

However this won't work on Ubuntu as this time, as they are not configured as services.

The packaging should install mesos-master and mesos-slave as services so they can be managed with the "service" command.

Note that this does work:

    start mesos-master
    start mesos-slave

**Comment by ssk2** [comment]
@swartzrock - this is because Ubuntu currently uses Upstart (e.g. http://askubuntu.com/questions/58404/how-to-start-and-stop-a-service), their alternative to systemd. I believe this is by design and we should fix our documentation :).

**Comment by swartzrock** [comment]
It would be great to have the same command "service start mesos-master" work across Linux releases. Is there a problem with additionally configuring these as services? Note that Marathon is configured with both upstart and as a service in Ubuntu.

**Comment by jsancio** [comment]
@swartzrock what error do you get? It should be `sudo service mesos-master (start | stop | restart)`

**Comment by swartzrock** [comment]
@jsancio huh, you're right.
