### ISSUE TITLE
What is the realpath binary used?

### ISSUE THREAD

**Issue by radekg** [mesosphere/mesos-deb-packaging#73]
There was a change done 4 days ago:
https://github.com/mesosphere/mesos-deb-packaging/commit/f7bf8e883ddb01e66ac98c27420846503cbd46ac#diff-4b50484efae8f6de7189b46016875ddaR168

I wonder, what is that `realpath`? I'm looking at man for `realpath`: http://manpages.ubuntu.com/manpages/trusty/man1/realpath.1.html
and I can't see any documentation for `--relative-to`. Where does it come from?

Also, neither docker `ubuntu:precise`, neither `ubuntu:trusty` has `realpath` available. This prevents Mesos from building inside of the Docker container.

**Comment by karya0** [comment]
Apparently, this option for realpath first came in Utopic (http://manpages.ubuntu.com/manpages/utopic/man1/realpath.1.html) which means it's not available for trusty or precise. I have reverted the change for now. Will generate a new PR.

**Comment by radekg** [comment]
Thank you.

**Comment by karya0** [comment]
@radekg: Can you take a look at https://github.com/mesosphere/mesos-deb-packaging/pull/74/ and see if that would work?

**Comment by radekg** [comment]
I can test this shortly.

**Comment by radekg** [comment]
Tried on precise and went to `make` successfully. It should work perfectly fine on `trusty` and higher.

**Comment by radekg** [comment]
I see this has been merged. 👍
