### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by bwhaley** [mesosphere/mesos-deb-packaging#78]
Following up on [a post to the mailing list](http://mail-archives.apache.org/mod_mbox/mesos-user/201604.mbox/%3CCA%2BfJHLhjRGN-QTCRjMKCgc8Cpx%2BgPjYDTs6Q8aao3C2wYj5JuQ%40mail.gmail.com%3E), it would be great to have SSL enabled in the packages. I don't see it in the 0.29 nightly builds yet.

Can this be added in the v0.29 release?

**Comment by EliotBerriot** [comment]
I second this, I did not find a simple way to build a mesos package for debian with SSL.

**Comment by bwhaley** [comment]
Wow this has been solved for months but somehow I missed it. Thank you!!
