### ISSUE TITLE
Ubuntu Xenial (16.04) package for Mesos 1.0.1 broken

### ISSUE THREAD

**Issue by uromahn** [mesosphere/mesos-deb-packaging#90]
I am trying to install mesos 1.0.1 from the published deb package available at "http://repos.mesosphere.com/ubuntu xenial main". During the installation process with "sudo apt install mesos" I am getting the following error message:

`Preparing to unpack .../mesos_1.0.1-2.0.93.ubuntu1604_amd64.deb ...
Unpacking mesos (1.0.1-2.0.93.ubuntu1604) ...
dpkg-deb (subprocess): cannot copy archive member from '/var/cache/apt/archives/mesos_1.0.1-2.0.93.ubuntu1604_amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb: error: subprocess paste returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/mesos_1.0.1-2.0.93.ubuntu1604_amd64.deb (--unpack):
 cannot copy extracted data for './usr/share/mesos/webui/master/static/js/jquery-1.7.1.js' to '/usr/share/mesos/webui/master/static/js/jquery-1.7.1.js.dpkg-new': unexpected end of file or stream`

It appears that the deb file is broken.

**Comment by uromahn** [comment]
Appears that a new deb package has been created and published to the Ubuntu repo, so I am closing my own issue here. :)

**Comment by karya0** [comment]
It was a glitch in the process of uploading the deb file to the ubuntu repo that corrupted the file. I have now uploaded a newer version. Please check this out and reopen this ticket if it still doesn't work.
